-   id: check-er-suffix
    name: check-er-suffix
    description: check if any class ends with "-er"
    entry: check-er-suffix
    language: python
    stages: [commit, push, manual]
-   id: check-getters-setters
    name: check-getters-setters
    description: check the code for any getters and setters
    entry: check-getters-setters
    language: python
    stages: [commit, push, manual]

